(() => {
'use strict';

const day = new Audio('audio/day.mp3');
const night = new Audio('audio/night.mp3');
day.loop = night.loop = true;
day.volume = night.volume = 0.45;
let musicOn = false;
let current = null;
let shade = null;

const css = document.createElement('style');
css.textContent = '#muneoulgolMusic{position:fixed;right:18px;bottom:18px;z-index:99999;background:rgba(31,25,20,.94);color:#ded4c1;border:1px solid #6e5a40;border-radius:10px;padding:9px 12px;font:14px system-ui,sans-serif}#ch1Shade{position:absolute;inset:0;background:rgba(0,0,0,.60);box-shadow:inset 0 0 140px rgba(0,0,0,.9);z-index:4;pointer-events:none;display:none}#ch1Mark{position:fixed;left:10px;bottom:10px;z-index:99999;color:#b7925d;background:rgba(20,15,10,.75);border:1px solid #4a3b2c;padding:3px 6px;font:11px system-ui}#muneoulgolPad,#muneoulgolAction,#muneoulgolUnlock{display:none!important}';
const music = document.createElement('button');
music.id = 'muneoulgolMusic';
music.textContent = '음악 켜기';
const mark = document.createElement('div');
mark.id = 'ch1Mark';
mark.textContent = 'expansion v2026-06-10i';

document.addEventListener('DOMContentLoaded', () => {
  document.head.appendChild(css);
  document.body.appendChild(music);
  document.body.appendChild(mark);
  const gamebox = document.querySelector('.gamebox');
  if (gamebox) {
    shade = document.createElement('div');
    shade.id = 'ch1Shade';
    gamebox.appendChild(shade);
  }
  cleanup();
});

function cleanup(){ ['muneoulgolPad','muneoulgolAction','muneoulgolUnlock'].forEach(id => document.getElementById(id)?.remove()); }
function txt(id){ return document.getElementById(id)?.innerText || ''; }
function fullText(){ return txt('hud') + '\n' + txt('phaseText') + '\n' + txt('speaker') + '\n' + txt('dialogText'); }
function isNight(){ return P.stage === 'night1' || P.stage === 'night2' || Q.stage === 'night'; }
function updateShade(){ if (shade) shade.style.display = isNight() && ((P.active && !P.done) || (Q.active && !Q.done)) ? 'block' : 'none'; }
async function play(k){ const target=k==='night'?night:day, other=k==='night'?day:night; if(current===target&&!target.paused)return; other.pause(); other.currentTime=0; current=target; try{await target.play();}catch{musicOn=false;} music.textContent=musicOn?(k==='night'?'밤 음악 재생 중':'낮 음악 재생 중'):'음악 켜기'; }
music.onclick=()=>{ musicOn=!musicOn; if(!musicOn){day.pause();night.pause();music.textContent='음악 켜기';return;} play(isNight()?'night':'day'); };
setInterval(()=>{ cleanup(); updateShade(); maybeStartCh2(); if(musicOn) play(isNight()?'night':'day'); },800);

const LOC={'촌장집':'chief','마을 우물':'well','무당집':'shaman','방앗간':'mill','관아 임시처소':'office','물소리 골짜기':'valley','벌목터':'lumber','무너진 산제단':'shrine','금지된 숲 입구':'forest','물소리 골짜기 방향':'toNorth','무너울골 남쪽 길':'toVillage','남쪽 고갯길':'toPass'};
const ACTION=new Set(['Enter',' ','z','Z']);
const P={active:false,done:false,dialog:false,stage:'d1',day:1,count:0,max:3,seen:{},off:[],note:[],clue:[],bias:{beast:0,human:0,ritual:0,conceal:0,unknown:0}};
const Q={active:false,done:false,dialog:false,stage:'wait',count:0,max:4,seen:{},off:[],note:[],clue:[],bias:{valley:0,human:0,ritual:0,conceal:0,unknown:0}};

function inCh1(){const h=fullText();return !P.done&&(P.active||(h.includes('무너울골')&&!/[2345]장/.test(h)&&h.includes('1장')));}
function inCh2(){const h=fullText();return P.done&&!Q.done&&(Q.active||h.includes('2장')||h.includes('물소리 골짜기'));}
function loc(){const m=txt('hud').match(/상호작용:\s*([^\n]+)/);return m?LOC[m[1].trim()]:null;}
function oldDialog(){const d=document.getElementById('dialog');return d&&!P.dialog&&!Q.dialog&&(d.style.display==='block'||(d.style.display===''&&txt('speaker')));}
function reportOpen(){return document.getElementById('reportPanel')?.style.display==='block';}
function add(a,v){if(v&&!a.includes(v))a.push(v);}
function fx(target,e={}){const B=target.bias;(e.b||[]).forEach(([k,n])=>{if(B[k]!==undefined)B[k]+=n;});(e.o||[]).forEach(v=>add(target.off,v));(e.n||[]).forEach(v=>add(target.note,v));(e.c||[]).forEach(v=>add(target.clue,v));}
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
function toast(m){const t=document.getElementById('toast');if(!t)return;t.textContent=m;t.style.display='block';clearTimeout(toast.id);toast.id=setTimeout(()=>t.style.display='none',1600);}
function labelP(){return {d1:'첫날 낮',report:'첫 보고',night1:'첫날 밤',d2:'둘째 낮',dusk:'둘째 해질녘',night2:'두 번째 밤',end:'새벽 정리'}[P.stage]||P.stage;}
function labelQ(){return {intro:'도입',day:'북쪽 낮 조사',report:'2장 중간 보고',night:'2장 밤',end:'새벽 정리'}[Q.stage]||Q.stage;}
function side(){const ph=document.getElementById('phaseText'),off=document.getElementById('official'),un=document.getElementById('unofficial'),cl=document.getElementById('cluePills');if(Q.active&&!Q.done){if(ph)ph.textContent=`2장 확장 · ${labelQ()} · 조사 ${Q.count}/${Q.max}`;if(off)off.innerHTML=Q.off.map(v=>`<li>${esc(v)}</li>`).join('')||'<li class="small">아직 없음</li>';if(un)un.innerHTML=Q.note.map(v=>`<li>${esc(v)}</li>`).join('')||'<li class="small">아직 없음</li>';if(cl)cl.innerHTML=Q.clue.map(v=>`<span class="pill">단서: ${esc(v)}</span>`).join('')||'<span class="small">아직 없음</span>';updateShade();return;}if(!P.active||P.done)return;if(ph)ph.textContent=`1장 확장 · ${P.day}일차 · ${labelP()} · 조사 ${P.count}/${P.max}`;if(off)off.innerHTML=P.off.map(v=>`<li>${esc(v)}</li>`).join('')||'<li class="small">아직 없음</li>';if(un)un.innerHTML=P.note.map(v=>`<li>${esc(v)}</li>`).join('')||'<li class="small">아직 없음</li>';if(cl)cl.innerHTML=P.clue.map(v=>`<span class="pill">단서: ${esc(v)}</span>`).join('')||'<span class="small">아직 없음</span>';updateShade();}
function closeDialog(){const d=document.getElementById('dialog');if(d)d.style.display='none';P.dialog=false;Q.dialog=false;side();}
function showFor(target,sp,body,opts){const d=document.getElementById('dialog'),s=document.getElementById('speaker'),tx=document.getElementById('dialogText'),box=document.getElementById('options');if(!d||!s||!tx||!box)return;target.active=true;target.dialog=true;if(target===P)Q.dialog=false;else P.dialog=false;s.textContent=sp;tx.textContent=body;box.innerHTML='';opts.forEach((op,i)=>{const b=document.createElement('button');b.textContent=`${i+1}. ${op.text}`;b.onclick=()=>{fx(target,op.e);if(op.response)respondFor(target,op.response,op.run);else{if(!op.keep)closeDialog();if(op.run)op.run();}side();};box.appendChild(b);});d.style.display='block';side();}
function respondFor(target,body,next){showFor(target,'기록 반응',body,[{text:'계속한다',run:next||closeDialog}]);}
function show(sp,body,opts){showFor(P,sp,body,opts);}function respond(body,next){respondFor(P,body,next);}function opt(text,e,response){return {text,e,response};}
function seenP(place){const k=P.stage+':'+place;if(P.seen[k]){toast('이미 조사한 곳이다. 다른 장소를 보자.');return false;}P.seen[k]=true;P.count++;return true;}
function seenQ(place){const k=Q.stage+':'+place;if(Q.seen[k]){toast('이미 2장 기록에 올린 장소다. 다른 흔적을 보자.');return false;}Q.seen[k]=true;Q.count++;return true;}
function afterP(){if(P.count>=P.max){if(P.stage==='d1')report1();else if(P.stage==='d2')dusk2();}else toast(`조사 ${P.count}/${P.max} 완료. 다른 장소로 이동하자.`);}
function afterQ(){if(Q.count>=Q.max)ch2Report();else toast(`2장 조사 ${Q.count}/${Q.max} 완료. 북쪽과 마을을 더 대조하자.`);}
function sceneP(title,body,opts,place){show(title,body,opts.map(o=>({...o,run:()=>{if(seenP(place))afterP();}})));}
function sceneQ(title,body,opts,place){showFor(Q,title,body,opts.map(o=>({...o,run:()=>{if(seenQ(place))afterQ();}})));}

function handleP(place){P.active=true;if(P.stage==='d1')return day1(place);if(P.stage==='night1')return night1(place);if(P.stage==='d2')return day2(place);if(P.stage==='night2')return night2(place);if(P.stage==='end')return place==='office'?finishBridge():toast('관아 임시처소에서 마무리하자.');}
function day1(place){if(!['chief','well','shaman','mill'].includes(place))return toast('촌장집, 우물, 무당집, 방앗간을 조사하자.');const D={chief:['을파의 장부','촌장집 마루는 볕을 잘 받는데도 장부 위만 눅눅하다. 을파는 당신이 앉기도 전에 장부를 펴고, 펴는 순간 손바닥으로 한 칸을 가린다.\n\n그 칸에는 산제에 쓴 쌀과 술의 수량이 있어야 했다. 그러나 먹이 번진 빈칸만 남아 있다.',[opt('범의 흔적으로 본다.',{b:[['beast',1]],o:['촌장 진술: 범 가능성']},'을파는 기다렸다는 듯 고개를 끄덕인다. “그렇게 적으면 마을이 덜 흔들릴 겁니다.” 그 말은 걱정처럼 들리지만, 부탁처럼도 들린다.'),opt('산제 중단과 연결한다.',{b:[['ritual',1]],c:['산제 비용 공백']},'당신이 빈칸을 짚자 을파의 손가락이 잠깐 굳는다. 이 칸만은 누군가 일부러 기억하지 않기로 한 듯 비어 있다.'),opt('기록 정리를 의심한다.',{b:[['conceal',1]],n:['장부가 지나치게 정리되어 있다']},'장부는 이상할 만큼 깨끗하다. 지저분한 마을의 장부가 아니라, 누군가 나중에 보여주려고 고른 종이 같다.')]],well:['우물가','우물가에는 아이들이 남긴 발자국이 겹겹이 말라 있다. 물동이를 내려놓은 흔적, 허둥지둥 달아난 발끝, 그리고 그 위를 지워 밟은 어른의 발자국.\n\n물은 조용한데, 우물 안쪽에서 산길 물소리가 난다.',[opt('도리의 이름을 확인한다.',{b:[['human',1]],o:['이름 확인: 도리'],c:['도리의 이름']},'월선은 이름을 듣자마자 고개를 든다. “도리요. 아직 도리라고 불러야 합니다.” 그 말 끝에서 우물물이 아주 작게 흔들린다.'),opt('산제 노래를 묻는다.',{b:[['ritual',1]],c:['산제 노래']},'한 아이가 노래의 첫 구절을 부르다 말고 입을 다문다. 금지된 노래는 사라진 아이보다 오래 마을에 남아 있었던 것 같다.'),opt('주민 침묵을 본다.',{b:[['conceal',1]],n:['사람들이 서로 눈치를 본다']},'누구도 거짓말을 하고 있지는 않다. 다만 모두가 말하지 않기로 한 문장 앞에서 입술을 닫고 있다.')]],shaman:['막례의 말','무당집 처마 밑 금줄은 오래되어 누렇게 말랐다. 그런데 매듭 하나만 새 짚이다. 막례는 그것을 보라는 듯 내버려 둔다.\n\n“산은 기록을 못 해. 대신 사람이 산 대신 거짓말을 하지.”',[opt('산제 의미를 묻는다.',{b:[['ritual',1]],c:['검은등 별칭']},'막례는 방울을 흔들지 않는다. 흔들지 않는데도 쇳소리가 난다. “검은등은 이름이 아니야. 등을 보였다는 뜻이지.”'),opt('사람의 개입을 묻는다.',{b:[['human',1]],n:['사람이 산 이름을 빌릴 때가 있다']},'“산이 아이를 부를 때도 있고, 사람이 산 목소리를 흉내 낼 때도 있어. 문제는 둘이 같은 소리로 들린다는 거야.”'),opt('공식 감시 대상으로 본다.',{b:[['conceal',1]],o:['무당 감시 필요성']},'“관아 문서에 내 이름을 올려. 대신 아이 이름도 같이 올려. 어른 이름만 남는 보고서는 늘 사람을 덜 죽인 척하거든.”')]],mill:['방앗간','방앗간은 낮인데도 서늘하다. 물레는 멈췄고 물길도 막혔는데, 축에는 방금 젖은 듯한 물방울이 맺혀 있다.\n\n돌확 아래에는 짚신에서 빠진 것처럼 가늘고 찢긴 풀 조각 하나가 끼어 있다.',[opt('풀 조각을 챙긴다.',{b:[['human',1]],c:['짚신 풀 조각']},'풀 조각은 끌려간 흔적이라기보다는, 붙잡힌 쪽이 버틴 흔적에 가깝다. 당신은 그것을 먼저 손안에 숨긴다.'),opt('물기를 확인한다.',{b:[['ritual',1]],c:['젖은 물레 축']},'물은 차갑지 않다. 손끝에 닿는 순간 오래된 제삿술 냄새가 난다. 방앗간의 물은 흐르지 않았지만, 무언가 이곳을 지나갔다.'),opt('검은 털을 줍는다.',{b:[['beast',1]],c:['검은 털']},'검은 털은 범의 것이라 적기에는 너무 젖어 있고, 사람의 것이라 하기에는 너무 거칠다. 기록하기 쉬운 단서일수록 거짓말을 하기 쉽다.')]]}[place];sceneP(D[0],D[1],D[2],place);}
function report1(){P.stage='report';P.active=true;P.dialog=false;const d=document.getElementById('dialog');if(d)d.style.display='none';openFirstReportPanel();side();}
function buildReport(groupsBox,report,groups){groupsBox.innerHTML='';groups.forEach(g=>{const div=document.createElement('div');div.className='reportGroup';div.innerHTML='<b>'+g.title+'</b><div class="choices"></div>';const box=div.querySelector('.choices');g.items.forEach(item=>{const b=document.createElement('button');b.textContent=item;b.onclick=()=>{report[g.key]=item;[...box.children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected');};box.appendChild(b);});groupsBox.appendChild(div);});}
function openFirstReportPanel(){const panel=document.getElementById('reportPanel'),title=document.getElementById('reportTitle'),intro=document.getElementById('reportIntro'),groupsBox=document.getElementById('reportGroups'),finishBtn=document.getElementById('finishReport');if(!panel||!title||!intro||!groupsBox||!finishBtn)return;const report={cause:null,measure:null,missing:null};title.textContent='1장 중간 보고서';intro.textContent='첫날 낮 조사 결과를 관아 문장으로 정리합니다. 무엇을 쓰느냐보다 무엇을 빼느냐가 더 오래 남습니다. 제출 후 1일차 밤 조사로 이어집니다.';buildReport(groupsBox,report,[{key:'cause',title:'사건 원인',items:['범의 흔적','사람의 흔적','산제 흔적','마을 은폐','판단 보류']},{key:'measure',title:'조치',items:['산길 폐쇄','추가 조사','촌장 책임 조사','무당 협조','수색 지속']},{key:'missing',title:'실종자 표기',items:['생존 가능성 있음','행방 불명','호적 보류','사망 추정']}]);finishBtn.onclick=()=>{if(!report.cause||!report.measure||!report.missing){toast('모든 항목을 하나씩 선택하세요.');return;}add(P.off,'1장 첫 보고: '+report.cause+' / '+report.measure+' / '+report.missing);if(report.cause.includes('범'))P.bias.beast+=2;else if(report.cause.includes('사람'))P.bias.human+=2;else if(report.cause.includes('산제'))P.bias.ritual+=2;else if(report.cause.includes('은폐'))P.bias.conceal+=2;else P.bias.unknown+=2;panel.style.display='none';respond('중간 보고서가 접수되었다. 종이는 금세 마르지만, 거기에 쓰지 않은 말들은 젖은 채로 남는다.\n\n밤이 되자 마을은 보고서에 적힌 문장과 다른 소리를 내기 시작한다.',startNight1);};panel.style.display='block';}
function startNight1(){P.day=1;P.stage='night1';P.count=0;P.max=1;updateShade();show('1일차 밤','첫 보고서를 올렸지만 밤은 아직 끝나지 않았다.\n\n관아에 보낸 문장은 마을을 조용하게 만들었지만, 조용해진 자리마다 다른 소리가 고인다. 우물, 무당집, 방앗간 중 한 곳을 확인하자.',[{text:'밤 조사를 시작한다',run:closeDialog}]);}
function finishNight1(afterText){show('새벽 기록',afterText,[{text:'2일차 아침으로 넘긴다',run:()=>beginDay2('night')}]);}
function night1(place){if(!['well','shaman','mill'].includes(place))return toast('첫날 밤에는 우물, 무당집, 방앗간 중 한 곳만 확인하자.');const D={well:{title:'첫날 밤의 우물',body:'우물가에는 아무도 없다. 그런데 누가 방금 물을 길어 간 듯 바닥이 젖어 있다. 두레박 줄은 내려가 있지 않은데, 물 위에는 장승 그림자가 비친다. 장승은 우물가에 서 있지 않다.',e:{b:[['ritual',1]],c:['우물의 이름 반응'],n:['도리 이름에 우물이 반응했다']},response:'당신은 도리의 이름을 기록장 가장자리에 적는다. 먹이 번지기도 전에 우물 안쪽에서 같은 이름이 아주 작게 되돌아온다. 메아리라기에는 너무 늦고, 대답이라기에는 너무 낮다.',after:'첫날 밤 기록: 우물은 범의 발자국도, 사람의 손자국도 내놓지 않았다. 대신 이름에 반응했다.\n\n공식 보고서에는 쓰기 어려운 사실이다. 그러나 2일차에는 월선에게 도리의 이름, 노래, 우물가에서 마지막으로 본 사람을 다시 물어야 한다.'},shaman:{title:'첫날 밤의 무당집',body:'무당집에는 등불이 없다. 그런데 금줄의 짚 끝마다 희미한 빛이 걸려 있다. 막례는 당신이 올 것을 이미 알고 있었던 사람처럼 말한다.\n\n“보고서에 적은 말이 밤을 부른다.”',e:{b:[['ritual',1]],c:['밤의 금줄'],n:['막례는 창귀 가능성을 에둘러 말했다']},response:'막례는 끝내 검은등이라는 이름을 입 밖에 내지 않는다. 대신 문턱 아래를 손가락으로 누른다. 그곳에는 아이 손톱보다 작은 짚 조각이 끼어 있다.',after:'첫날 밤 기록: 막례는 산이 아이를 데려갔다고 말하지 않았다. 다만 사람이 산의 이름을 빌릴 수 있다고 했다.\n\n2일차에는 무당집 뒤뜰, 금줄 매듭, 오래된 제문을 함께 봐야 한다.'},mill:{title:'첫날 밤의 방앗간',body:'방앗간의 물레는 멈춰 있다. 하지만 멈춘 물레에서 물이 도는 소리만 빠져나온다. 나무 바닥은 오래된 쌀겨 냄새와 새로 젖은 짚 냄새를 함께 품고 있다.',e:{b:[['human',1],['ritual',1]],c:['밤 방앗간의 물소리'],n:['방앗간에서 아이 목소리 같은 소리를 들었다']},response:'물레 소리 사이로 아주 낮은 목소리가 섞인다. 아이 목소리 같기도 하고, 어른이 아이 흉내를 내는 소리 같기도 하다.\n\n산의 소리와 사람의 흔적이 같은 곳에 남았다.',after:'첫날 밤 기록: 방앗간은 산의 흔적과 사람의 흔적을 동시에 남겼다. 어느 한쪽만 적으면 나머지 하나가 거짓이 된다.\n\n2일차에는 방앗간의 짚 조각, 촌장집 장부의 빈칸, 마을 뒤편의 젖은 짚 냄새를 서로 대조해야 한다.'}}[place];show(D.title,D.body,[{text:'밤의 흔적을 기록한다',e:D.e,response:D.response,run:()=>finishNight1(D.after)}]);}
function beginDay2(k){P.day=2;P.stage='d2';P.count=0;P.max=2;const m={night:'첫날 밤의 기록이 마을의 낮을 바꾸었다. 어제의 보고서는 끝난 문서가 아니라, 오늘의 의심을 여는 문이 되었다.'}[k]||'둘째 날이 밝았다.';show('2일차 아침',m,[{text:'둘째 날 조사를 시작한다',run:closeDialog}]);}
function day2(place){if(!['chief','well','shaman','mill'].includes(place))return toast('마을 핵심 장소를 다시 확인하자.');const D={chief:['2일차 촌장집','을파는 장부를 닫지 않는다. 어제는 손바닥으로 가리던 칸을 오늘은 일부러 열어 둔다. 빈칸은 여전히 빈칸이다.',[opt('은폐 정황을 묻는다.',{b:[['conceal',1]],n:['을파는 헛간 이야기에 표정을 닫았다']},'을파는 “마을을 지키는 일과 마을을 의심하는 일이 늘 다르진 않다”고 말한다.'),opt('마루 이름을 확인한다.',{b:[['human',1]],c:['마루 이름']},'마루라는 이름은 장부의 가장자리에서 발견된다. 정식 호적 칸이 아니라, 빚과 품삯을 적는 난외다.')]],well:['2일차 우물가','월선은 우물가에 앉아 도리의 이름을 반복하고 있다. 이름을 부르는 것이 기도인지 확인인지 분간되지 않는다.',[opt('도리 이름을 기록한다.',{b:[['human',1]],o:['도리 이름 공식 기록'],c:['도리의 이름']},'이름이 공식 기록에 오른다는 말에 월선의 어깨가 아주 조금 내려간다.'),opt('노래를 더 묻는다.',{b:[['ritual',1]],c:['노래 조각']},'월선은 노래를 모른다고 한다. 하지만 마지막 음만은 따라 부른다.')]],shaman:['2일차 막례','막례는 젖은 돌을 볕에 말리고 있다. 돌은 마르지 않는다. “물에 젖은 게 아니야. 이름에 젖은 거지.”',[opt('산제 관련성을 묻는다.',{b:[['ritual',1]],n:['막례는 말을 아꼈다']},'막례는 산제는 빌기 위한 자리가 아니라 돌려보내기 위한 자리였다고 말한다.'),opt('비공식 기록에 남긴다.',{b:[['unknown',1]],n:['산의 등은 검고 물의 입은 닫히지 않는다']},'당신은 관아 문서가 아닌 쪽지에 적는다. 막례는 그 문장을 보고 처음으로 고개를 끄덕인다.')]],mill:['2일차 방앗간','방앗간의 물레는 완전히 말랐다. 말랐기 때문에 더 수상하다. 밤새 젖어 있던 냄새가 한순간에 사라진 자리에, 누군가 쓸고 간 자국만 남아 있다.',[opt('검은 털을 보관한다.',{b:[['beast',1]],c:['젖은 검은 털']},'검은 털은 아침이 되자 조금 가벼워졌다. 너무 빨리 보여주면 다른 흔적들이 그 이름 아래 묻힐 것이다.'),opt('돌확을 조사한다.',{b:[['ritual',1]],c:['돌확 절차']},'돌확의 홈은 물길이 아니라 사람 손으로 판 선이다. 그 선은 산 쪽을 향하다가 마지막에 마을 안쪽으로 꺾인다.')]]}[place];sceneP(D[0],D[1],D[2],place);}
function dusk2(){P.stage='dusk';show('2일차 해질녘','해가 산등성이에 걸리자 마을은 다시 두 갈래로 갈라진다. 하나는 관아에 적기 쉬운 길이다. 다른 하나는 아직 이름 붙이기 어려운 길이다.',[{text:'을파의 설명을 따른다',e:{b:[['beast',1]]},response:'을파는 고개를 숙인다. 마을은 잠시 안정된다. 하지만 안정된 마을일수록 누군가의 울음소리는 더 멀리 밀려난다.',run:startNight2},{text:'월선의 증언을 믿는다',e:{b:[['human',1]]},response:'월선은 도리의 이름을 다시 붙잡는다. 그 이름은 아이가 아직 사람으로 남아 있다는 마지막 끈처럼 느껴진다.',run:startNight2},{text:'막례의 경고를 듣는다',e:{b:[['ritual',1]]},response:'막례가 금줄을 한 겹 더 묶는다. 무언가가 밤에 들어오지 못하게 하려는 손이다.',run:startNight2},{text:'누구도 완전히 믿지 않는다',e:{b:[['unknown',1]]},response:'모든 증언이 서로 다른 방향을 가리킨다. 당신은 어느 한쪽으로 기울지 않는 대신, 모든 쪽에서 미움을 살 준비를 한다.',run:startNight2}]);}
function startNight2(){P.stage='night2';P.count=0;P.max=1;updateShade();toast('두 번째 밤이다. 화면이 어두워졌다.');}
function night2(place){if(!['chief','well','shaman','mill'].includes(place))return toast('밤에는 핵심 장소 한 곳만 보자.');const D={chief:['헛간 쪽 밤','젖은 짚 냄새가 난다. 낮에는 없던 냄새다.',{b:[['conceal',1]],c:['젖은 짚단']}],well:['우물의 밤','물은 같은 이름을 여러 사람의 목소리로 나누어 돌려준다.',{b:[['ritual',1]],c:['이름 반응']}],shaman:['금줄의 밤','금줄이 한 겹 더 매인다. 오래된 의례는 기도보다 수선에 가깝다.',{b:[['ritual',1]],c:['제문 조각']}],mill:['돌확의 밤','물이 없는 곳에서 물소리가 난다는 것은, 물이 아니라 길이 흐른다는 뜻일지도 모른다.',{b:[['unknown',1]],n:['물소리 속에 여러 이름이 섞였다']}]}[place];show(D[0],D[1],[{text:'새벽까지 기록한다',e:D[2],response:'밤의 기록이 끝났다. 새벽이 오자 어둠이 조금 물러난다. 하지만 남은 것은 더 선명해진 발자국이다.',run:end1}]);}
function end1(){P.stage='end';updateShade();show('1장 종료','도리는 돌아오지 않았다.\n\n하지만 이제 그는 단순한 실종자가 아니다. 보고서에 적힌 이름, 우물에 되돌아온 이름, 누군가 숨기려 한 이름이 되었다.\n\n물소리 골짜기는 그 이름들을 한꺼번에 삼키고 있다.',[{text:'원본 보고서 화면을 연다',run:finish}]);}
function finishBridge(){show('원본 2장 연결','1장 확장 이벤트가 끝났다. 이제 관아에 올릴 마지막 1장 보고서를 정리하고, 물소리 골짜기로 넘어간다.',[{text:'원본 보고서 작성 화면을 연다',run:finish}]);}
function finish(){P.done=true;closeDialog();updateShade();toast('1장 확장 종료. 원본 2장으로 이어집니다.');try{window.openReport&&window.openReport(1);}catch{}}
function maybeStartCh2(){if(!P.done||Q.active||Q.done||reportOpen()||P.dialog||Q.dialog||oldDialog())return;const h=fullText();if(h.includes('2장')||h.includes('물소리 골짜기')){Q.active=true;Q.stage='intro';Q.count=0;Q.max=4;showFor(Q,'2장: 물소리 골짜기','관아에 1장 보고서가 올라가자, 마을 북쪽 길이 열린다.\n\n물소리 골짜기는 물이 많아서 그렇게 불리는 곳이 아니다. 물이 없는데도 물소리가 나서 그렇게 불린다.\n\n이번 장에서는 북쪽의 흔적과 마을 안쪽의 진술을 서로 대조해야 한다.',[{text:'2장 조사를 시작한다',run:()=>{Q.stage='day';closeDialog();}}]);}}
function handleQ(place){if(!Q.active||Q.done)return false;if(['toNorth','toVillage','toPass','forest'].includes(place))return false;if(Q.stage==='intro'){Q.stage='day';return true;}if(Q.stage==='day')return ch2Day(place);if(Q.stage==='night')return ch2Night(place);if(Q.stage==='end')return place==='office'?openFinalCh2Report():(toast('관아 임시처소에서 2장 보고서를 정리하자.'),true);return false;}
function ch2Day(place){const D={valley:['물소리 골짜기','골짜기에는 흐르는 물이 없다. 그런데 귀를 낮추면 돌 밑에서 물이 흐른다. 소리는 아래가 아니라 앞에서 오고, 앞이 아니라 등 뒤에서 닫힌다.\n\n발자국 몇 개가 같은 자리를 빙빙 돈다. 길을 잃은 흔적이라기보다, 길이 사람을 되돌려 보낸 흔적이다.',[opt('소리가 돌아오는 지점을 표시한다',{b:[['valley',1],['unknown',1]],c:['되돌아오는 물소리']},'표시한 돌은 세 번 확인해도 제자리가 아니다. 지도는 맞는데 길이 틀린다.'),opt('발자국의 순서를 본다',{b:[['human',1]],c:['반복된 발자국']},'가장 작은 발자국 위에 더 큰 발자국이 겹쳐 있다. 보호하려고 따라간 것인지, 끌고 간 것인지 아직 갈리지 않는다.')]],lumber:['벌목터','벌목터의 나무들은 베인 것이 아니라 멈춘 것처럼 서 있다. 도끼 자국은 중간에서 끊겼고, 나무 밑동에는 물에 불은 흙이 말라붙어 있다.\n\n사량이라는 사냥꾼은 당신을 보자 도끼부터 치운다.',[opt('사량의 덫을 확인한다',{b:[['human',1]],c:['사량의 빈 덫']},'덫은 짐승을 잡기 위한 모양이지만, 끈 높이가 아이 허리쯤에 걸려 있다.'),opt('벌목 중단 이유를 묻는다',{b:[['conceal',1]],n:['벌목터 사람들은 같은 날 일을 멈췄다']},'사량은 “나무가 울어서”라고 말한 뒤, 스스로도 그 말이 우스운 듯 입을 다문다.')]],shrine:['무너진 산제단','산제단은 무너져 있지만, 무너진 순서가 이상하다. 오래된 돌은 안쪽에 있고 새 돌은 바깥에 있다. 누군가 폐허를 고치려다 중간에 그만둔 흔적이다.\n\n제단 아래 홈에는 마른 잎 대신 젖은 쌀알 하나가 붙어 있다.',[opt('제단의 홈을 따라 본다',{b:[['ritual',1]],c:['산제단의 역방향 홈']},'홈은 산 위쪽으로 이어지지 않는다. 마을 쪽으로 돌아 나온다. 산제는 산을 향한 의식이 아니라, 돌아오는 것을 막는 절차였을지도 모른다.'),opt('젖은 쌀알을 챙긴다',{b:[['ritual',1],['conceal',1]],c:['젖은 제물 쌀']},'누군가 최근에 이곳에 왔다. 공식적으로 중단된 산제는 실제로는 완전히 끝나지 않았다.')]],chief:['2장 촌장집','을파는 북쪽 길 이야기가 나오자 창문을 닫는다. 바람 때문이라고 하지만, 방 안에는 바람이 없다.',[opt('북쪽 길 출입을 묻는다',{b:[['conceal',1]],n:['을파는 북쪽 출입 명단을 숨긴다']},'을파는 명단은 없다고 말한다. 그러나 장부 끈에는 방금 풀었다 묶은 자국이 남아 있다.'),opt('마루의 이름을 묻는다',{b:[['human',1]],c:['마루와 북쪽 길']},'마루라는 이름을 꺼내자 을파의 대답이 한 박자 늦어진다. 모르는 이름에 보이는 반응이 아니다.')]],well:['2장 우물가','우물가의 물소리와 골짜기의 물소리가 같은 박자로 겹친다. 월선은 그것을 듣고도 놀라지 않는다.',[opt('월선에게 같은 소리를 들었는지 묻는다',{b:[['human',1]],n:['월선은 밤마다 같은 물소리를 들었다']},'월선은 “도리가 사라진 뒤로 물이 말을 배웠다”고 말한다.'),opt('아이들의 노래를 다시 묻는다',{b:[['ritual',1]],c:['되풀이되는 노래 끝음']},'아이들은 앞 구절은 잊었다고 하지만 끝음만은 정확히 맞춘다. 잊은 것이 아니라 지운 것이다.')]],shaman:['2장 무당집','막례는 북쪽을 보지 않는다. 보지 않는 쪽을 너무 잘 아는 사람의 태도다.',[opt('검은등의 자리를 묻는다',{b:[['ritual',1]],c:['검은등의 자리']},'“자리는 산에 있지 않아. 사람이 비워 둔 곳에 생겨.” 막례의 말은 수수께끼보다 진술에 가깝다.'),opt('산제 복원 여부를 묻는다',{b:[['ritual',1],['conceal',1]],n:['산제는 중단된 것이 아니라 숨겨졌다']},'막례는 복원이 아니라 봉합이라고 고쳐 말한다. 찢어진 것이 아직 벌어져 있다는 뜻이다.')]],mill:['2장 방앗간','방앗간의 물레 소리가 골짜기 쪽과 엇박으로 돈다. 두 소리는 닮았지만 같은 곳에서 나지 않는다.',[opt('물레 축과 골짜기 돌을 대조한다',{b:[['unknown',1]],c:['엇박의 물소리']},'두 소리는 서로를 흉내 낸다. 하나가 원본이고 하나가 메아리라면, 어느 쪽이 먼저인지 아직 알 수 없다.'),opt('큰 발자국의 진흙을 묻는다',{b:[['human',1]],c:['북쪽 진흙 발자국']},'방앗간의 진흙은 북쪽 벌목터 흙과 색이 같다. 누군가는 마을과 골짜기를 오갔다.')]]}[place];if(!D)return false;sceneQ(D[0],D[1],D[2],place);return true;}
function ch2Report(){Q.stage='report';const panel=document.getElementById('reportPanel'),title=document.getElementById('reportTitle'),intro=document.getElementById('reportIntro'),groupsBox=document.getElementById('reportGroups'),finishBtn=document.getElementById('finishReport');if(!panel||!title||!intro||!groupsBox||!finishBtn)return;const report={cause:null,measure:null,route:null};title.textContent='2장 중간 보고서';intro.textContent='물소리 골짜기와 마을 내부 진술을 대조해 보고합니다. 선택한 문장은 밤 조사에서 무엇이 먼저 드러나는지 바꿉니다.';buildReport(groupsBox,report,[{key:'cause',title:'핵심 판단',items:['길 자체의 이상','사람의 유도','산제 절차의 파손','마을의 은폐','판단 보류']},{key:'measure',title:'즉시 조치',items:['북쪽 길 임시 봉쇄','벌목터 수색','산제단 보존','무당 협조 요청','아이 이름 대조']},{key:'route',title:'밤 조사 우선지',items:['우물의 물소리','무당집 금줄','무너진 산제단','방앗간 물레']}]);finishBtn.onclick=()=>{if(!report.cause||!report.measure||!report.route){toast('모든 항목을 하나씩 선택하세요.');return;}add(Q.off,'2장 중간 보고: '+report.cause+' / '+report.measure+' / '+report.route);panel.style.display='none';Q.stage='night';Q.count=0;Q.max=1;updateShade();respondFor(Q,'2장 중간 보고서가 접수되었다.\n\n그날 밤, 물소리는 한 곳에서 들리지 않았다. 보고서에 우선지로 적은 장소가 먼저 젖고, 그 다음에 마을의 다른 장소들이 늦게 따라 젖는다.',()=>showFor(Q,'2장 밤','우물, 무당집, 무너진 산제단, 방앗간 중 한 곳에서 밤의 반응을 확인하자.',[{text:'밤 조사를 시작한다',run:closeDialog}]););};panel.style.display='block';}
function ch2Night(place){const D={well:['2장 밤: 우물','우물물은 더 이상 이름 하나만 돌려주지 않는다. 도리, 마루, 그리고 아직 기록하지 않은 아이의 이름이 섞여 올라온다.\n\n이름들이 서로를 밀어내지 않는다. 마치 같은 길에서 돌아오지 못한 사람들처럼 한곳에 엉켜 있다.',{b:[['human',1],['ritual',1]],c:['섞여 돌아온 이름들']}],shaman:['2장 밤: 무당집','막례는 금줄을 끊어 불에 넣는다. 타는 냄새는 짚 냄새가 아니라 젖은 머리카락 냄새에 가깝다.\n\n“끊어야 묶이는 것도 있어.” 그녀는 그렇게 말한다.',{b:[['ritual',1]],c:['태운 금줄 재']}],shrine:['2장 밤: 산제단','무너진 산제단의 돌들이 낮과 다른 위치에 놓여 있다. 누가 옮긴 흔적은 없는데, 제단은 조금 더 완성된 모양에 가까워졌다.\n\n복원된 것이 아니라, 돌아오고 있다.',{b:[['ritual',1],['unknown',1]],c:['밤에 움직인 제단 돌']}],mill:['2장 밤: 방앗간','방앗간 물레와 골짜기 물소리가 처음으로 같은 박자에 맞는다. 그 순간 물레 그림자가 사람의 팔처럼 길어진다.\n\n누군가 돌렸거나, 무언가 돌게 만들었다.',{b:[['human',1],['unknown',1]],c:['물레 그림자의 팔']}]}[place];if(!D)return toast('2장 밤에는 우물, 무당집, 산제단, 방앗간 중 한 곳을 보자.'),true;showFor(Q,D[0],D[1],[{text:'밤의 결과를 기록한다',e:D[2],response:'2장 밤 기록이 끝났다. 이제 물소리 골짜기는 단순한 장소가 아니라, 마을이 숨긴 이름들이 되돌아오는 통로가 되었다.',run:()=>{Q.stage='end';updateShade();showFor(Q,'2장 종료','새벽이 오자 북쪽 길은 다시 평범한 산길처럼 보인다.\n\n하지만 이제 당신은 안다. 길이 이상한 것이 아니라, 기록되지 않은 이름들이 같은 길을 반복하고 있다는 것을. 관아 임시처소에서 2장 보고서를 정리하자.',[{text:'관아에서 2장 보고서를 작성한다',run:openFinalCh2Report}]);}}]);return true;}
function openFinalCh2Report(){Q.done=true;closeDialog();updateShade();toast('2장 확장 종료. 원본 2장 보고서로 이어집니다.');try{window.openReport&&window.openReport(2);}catch{}}
function adoptOriginalMidReport(){if(P.done)return;P.active=true;P.day=1;P.stage='night1';P.count=0;P.max=1;add(P.off,'1장 첫 보고: 중간 보고서 제출');const d=document.getElementById('dialog');if(d)d.style.display='none';P.dialog=false;show('1일차 밤','중간 보고서는 올라갔다. 하지만 보고서가 마을을 떠난 뒤에야, 보고서에 적히지 않은 것들이 움직이기 시작한다. 우물, 무당집, 방앗간 중 한 곳을 확인하자.',[{text:'밤 조사를 시작한다',run:closeDialog}]);}
document.addEventListener('click',e=>{const target=e.target&&e.target.closest?e.target.closest('#finishReport'):null;if(!target)return;const title=txt('reportTitle');if(!title.includes('1장 중간 보고서'))return;const selected=document.querySelectorAll('#reportPanel button.selected').length;if(selected<3)return;setTimeout(adoptOriginalMidReport,0);},false);
window.addEventListener('keydown',e=>{if(P.dialog||Q.dialog){const active=document.activeElement;if(ACTION.has(e.key)&&active&&active.closest&&active.closest('#options')){e.preventDefault();e.stopImmediatePropagation();active.click();return;}const n=parseInt(e.key,10);if(n>=1){const b=document.getElementById('options')?.children[n-1];if(b){e.preventDefault();e.stopImmediatePropagation();b.click();return;}}if(ACTION.has(e.key)){e.preventDefault();e.stopImmediatePropagation();}return;}if(!ACTION.has(e.key)||e.repeat||reportOpen()||oldDialog())return;const l=loc();if(!l)return;if(inCh2()){const handled=handleQ(l);if(handled){e.preventDefault();e.stopImmediatePropagation();}return;}if(inCh1()){e.preventDefault();e.stopImmediatePropagation();handleP(l);}},true);
setInterval(side,900);
})();